### ISSUE TITLE
接受offer时，neoline出现这个弹窗，感觉这个有点危险，看看是要修改合约还是和neoline沟通

### ISSUE THREAD

**Issue by FamelessLeo** [FamelessLeo/MegaOasis#10]
<img width="318" alt="Screen Shot 2022-07-15 at 4 15 05 PM" src="https://user-images.githubusercontent.com/87798080/179184024-fb00f4f9-a285-4fd8-9c45-8b888f04412b.png">

**Comment by ShaySong99** [comment]
已更新
