### ISSUE TITLE
普通list的NFT点击购买没有反应

### ISSUE THREAD

**Issue by superboyiii** [FamelessLeo/MegaOasis#13]
![1658214948707](https://user-images.githubusercontent.com/38493437/179689670-f29771b4-4f46-42db-9b82-f39b567fb61b.png)

![1658214280371](https://user-images.githubusercontent.com/38493437/179687470-d9cddced-6743-4eef-8131-26b04e8c76bf.png)

**Comment by ShaySong99** [comment]
已fix
